export const INTEGRATION_CATALOG = [
  {
    provider: "openai",
    label: "OpenAI",
    phase: "mvp",
    auth: "nango_api_key",
    description: "Use an OpenAI API key you provide to run AmbiOS agent workflows.",
  },
  {
    provider: "notion",
    label: "Notion",
    phase: "mvp",
    auth: "nango",
    description: "Read pages and databases, then prepare governed page changes.",
  },
  {
    provider: "cloudflare",
    label: "Cloudflare",
    phase: "mvp",
    auth: "nango",
    description: "Inspect accounts, zones, projects, and deployment evidence.",
  },
  {
    provider: "github",
    label: "GitHub",
    phase: "mvp",
    auth: "nango",
    description: "Inspect repositories, pull requests, checks, and deployment context.",
  },
  {
    provider: "vercel",
    label: "Vercel",
    phase: "mvp",
    auth: "nango",
    description: "Inspect teams, projects, and deployment history.",
  },
  {
    provider: "netlify",
    label: "Netlify",
    phase: "mvp",
    auth: "nango",
    description: "Inspect sites, teams, and deploy history.",
  },
  {
    provider: "shopify",
    label: "Shopify",
    phase: "mvp",
    auth: "nango",
    description: "Inspect products, inventory, and order context.",
  },
  {
    provider: "snyk",
    label: "Snyk",
    phase: "mvp",
    auth: "nango",
    description: "Inspect projects and dependency vulnerability findings.",
  },
  {
    provider: "socket",
    label: "Socket.dev",
    phase: "mvp",
    auth: "nango",
    description: "Analyze package supply-chain risk and security reports.",
  },
  {
    provider: "jira",
    label: "Jira",
    phase: "mvp",
    auth: "nango",
    description: "Verify authorized account access and inspect issue context.",
  },
  {
    provider: "google-drive",
    label: "Google Drive",
    phase: "mvp",
    auth: "nango",
    description: "Verify authorized file metadata access.",
  },
  {
    provider: "google-calendar",
    label: "Google Calendar",
    phase: "mvp",
    auth: "nango",
    description: "Verify authorized calendar access.",
  },
  {
    provider: "google-analytics",
    label: "Google Analytics",
    phase: "mvp",
    auth: "nango",
    description: "Verify authorized reporting access.",
  },
  {
    provider: "slack",
    label: "Slack",
    phase: "mvp",
    auth: "nango",
    description: "Verify authorized workspace access.",
  },
  {
    provider: "linear",
    label: "Linear",
    phase: "mvp",
    auth: "nango",
    description: "Verify authorized workspace access.",
  },
  {
    provider: "hubspot",
    label: "HubSpot",
    phase: "mvp",
    auth: "nango",
    description: "Verify authorized CRM access.",
  },
  {
    provider: "stripe",
    label: "Stripe",
    phase: "mvp",
    auth: "nango",
    description: "Verify authorized account metadata access.",
  },
  {
    provider: "figma",
    label: "Figma",
    phase: "mvp",
    auth: "nango",
    description: "Verify authorized file and team access.",
  },
  {
    provider: "framer",
    label: "Framer",
    phase: "mvp",
    auth: "nango",
    description: "Verify authorized site metadata access.",
  },
  {
    provider: "custom-rest",
    label: "Custom REST API",
    phase: "roadmap",
    auth: "api_token",
    description: "Cataloged for a future connector phase.",
  },
] as const;

export type IntegrationCatalogProvider = (typeof INTEGRATION_CATALOG)[number]["provider"];
export type IntegrationCatalogEntry = (typeof INTEGRATION_CATALOG)[number];

export const INTEGRATION_PERMISSIONS: Record<IntegrationCatalogProvider, readonly string[]> = {
  openai: ["Read permitted AmbiOS workspace context", "Create governed proposals"],
  notion: ["Read pages and databases", "Create and update pages"],
  cloudflare: [
    "Read account and project metadata",
    "Read deployments",
    "Trigger and inspect deployments",
  ],
  github: [
    "Read repositories and branches",
    "Read pull requests and checks",
    "Read Dependabot, code-scanning, and secret-scanning alerts",
    "Create or update deployment actions",
  ],
  vercel: ["Read team and project metadata", "Read deployments", "Trigger and inspect deployments"],
  netlify: ["Read site and team metadata", "Read deploys", "Trigger and inspect deploys"],
  shopify: ["Read products, inventory, and orders", "Create and update products and inventory"],
  snyk: ["Read projects and vulnerability findings", "Read dependency and license metadata"],
  socket: ["Analyze package supply-chain risk", "Read package security reports"],
  jira: ["Read projects and issues", "Create and update issues"],
  "google-drive": ["Read files and folders", "Read file metadata"],
  "google-calendar": ["Read and create calendar events", "Read calendars and attendees"],
  "google-analytics": ["Read analytics properties", "Read reports and metrics"],
  slack: ["Read workspace and channel metadata", "Read and send messages in authorized channels"],
  linear: ["Read teams, projects, and issues", "Create and update issues"],
  hubspot: ["Read CRM records", "Create and update authorized CRM records"],
  stripe: ["Read customers and payment metadata", "No payout or account-owner access"],
  figma: ["Read files, projects, and comments", "Prepare governed design-context proposals"],
  framer: ["Read sites and project metadata", "Prepare governed design proposals"],
  "custom-rest": ["Access only the API endpoints configured by you"],
};
