/**
 * Canonical HTTP operation registry.
 *
 * Raw AmbiOS route templates belong here (and only here). Consumers use an
 * operation ID plus path() so changing a route cannot silently leave a stale
 * caller behind. Schema names are stable contract identifiers; the runtime
 * adapters own the actual validator implementation.
 */
export type RuntimeOwner = "core-api" | "connector-execution" | "mcp-oauth";
export type Exposure = "public" | "protected";
export type Requirement = "none" | "required" | "optional";
export type Availability =
  | "live"
  | "preview"
  | "sandbox"
  | "not-configured"
  | "unverified"
  | "unsupported"
  | "deprecated";
export type OperationCategory =
  | "health"
  | "identity"
  | "auth"
  | "workspace"
  | "readiness"
  | "incidents"
  | "actions"
  | "approvals"
  | "guardrails"
  | "integrations"
  | "providers"
  | "resourceMappings"
  | "canvas"
  | "runs"
  | "console"
  | "audit"
  | "docs"
  | "artifacts"
  | "budget"
  | "sync"
  | "logs"
  | "deployment"
  | "hotfixes"
  | "webhooks"
  | "mcp"
  | "mcpOAuth"
  | "apiKeys"
  | "systems"
  | "services";

export type OperationDefinition = {
  readonly operationId: string;
  readonly category: OperationCategory;
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "ALL";
  readonly pathTemplate: string;
  readonly runtimeOwner: RuntimeOwner;
  readonly publicOrProtected: Exposure;
  readonly authenticationRequirement: Requirement;
  readonly organizationScopeRequirement: boolean;
  readonly workspaceScopeRequirement: boolean;
  readonly roleRequirement: string | null;
  readonly capabilityRequirement: string | null;
  readonly requestSchema: string | null;
  readonly responseSchema: string;
  readonly problemSchemas: readonly string[];
  readonly paginationSchema: string | null;
  readonly idempotencyRequirement: "none" | "recommended" | "required";
  readonly rateLimitCategory: "none" | "read" | "write" | "auth" | "webhook" | "provider";
  readonly auditRequirement: "none" | "optional" | "required";
  readonly queueRequirement: "none" | "producer" | "consumer";
  readonly providerRequirement: string | null;
  readonly verificationRequirement: "none" | "independent";
  readonly supportedStatus: Availability;
  readonly frontendAvailability: boolean;
  readonly webMcpAvailability: boolean;
  readonly remoteMcpAvailability: boolean;
  readonly documentationSummary: string;
  readonly deprecationStatus: "current" | "deprecated";
  readonly replacementOperationId: string | null;
  readonly sunsetDate: string | null;
  readonly migrationOwner: string | null;
  readonly clientMigrationStatus: "canonical" | "migrating" | "legacy";
  readonly examples: readonly string[];
};

type OperationInput = Omit<
  OperationDefinition,
  | "category"
  | "publicOrProtected"
  | "authenticationRequirement"
  | "organizationScopeRequirement"
  | "workspaceScopeRequirement"
  | "roleRequirement"
  | "capabilityRequirement"
  | "requestSchema"
  | "problemSchemas"
  | "paginationSchema"
  | "idempotencyRequirement"
  | "rateLimitCategory"
  | "auditRequirement"
  | "queueRequirement"
  | "providerRequirement"
  | "verificationRequirement"
  | "supportedStatus"
  | "frontendAvailability"
  | "webMcpAvailability"
  | "remoteMcpAvailability"
  | "deprecationStatus"
  | "replacementOperationId"
  | "sunsetDate"
  | "migrationOwner"
  | "clientMigrationStatus"
  | "examples"
> &
  Partial<
    Omit<
      OperationDefinition,
      | "operationId"
      | "method"
      | "pathTemplate"
      | "runtimeOwner"
      | "responseSchema"
      | "documentationSummary"
    >
  > &
  Pick<
    OperationDefinition,
    | "operationId"
    | "method"
    | "pathTemplate"
    | "runtimeOwner"
    | "responseSchema"
    | "documentationSummary"
  >;

const defaults: Omit<OperationDefinition, keyof OperationInput> = {
  category: "services",
  publicOrProtected: "protected",
  authenticationRequirement: "required",
  organizationScopeRequirement: true,
  workspaceScopeRequirement: true,
  roleRequirement: null,
  capabilityRequirement: null,
  requestSchema: null,
  problemSchemas: ["Problem"],
  paginationSchema: null,
  idempotencyRequirement: "none",
  rateLimitCategory: "read",
  auditRequirement: "optional",
  queueRequirement: "none",
  providerRequirement: null,
  verificationRequirement: "none",
  supportedStatus: "live",
  frontendAvailability: true,
  webMcpAvailability: false,
  remoteMcpAvailability: false,
  deprecationStatus: "current",
  replacementOperationId: null,
  sunsetDate: null,
  migrationOwner: null,
  clientMigrationStatus: "canonical",
  examples: [],
};

const defineOperation = <const T extends OperationInput>(input: T): OperationDefinition =>
  ({ ...defaults, ...input }) as OperationDefinition;

const defineLegacyOperation = <const T extends OperationInput>(input: T): OperationDefinition =>
  defineOperation({
    ...input,
    deprecationStatus: "deprecated",
    supportedStatus: "deprecated",
    clientMigrationStatus: "legacy",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
  });

export const operations = {
  getCoreRoot: defineOperation({
    operationId: "getCoreRoot",
    category: "health",
    method: "GET",
    pathTemplate: "/",
    runtimeOwner: "core-api",
    publicOrProtected: "public",
    authenticationRequirement: "none",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    responseSchema: "Health",
    documentationSummary: "Returns Core API readiness.",
  }),
  getCoreHealth: defineOperation({
    operationId: "getCoreHealth",
    category: "health",
    method: "GET",
    pathTemplate: "/health",
    runtimeOwner: "core-api",
    publicOrProtected: "public",
    authenticationRequirement: "none",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    responseSchema: "Health",
    documentationSummary: "Returns Core Worker health.",
  }),
  getConnectorRootHealth: defineOperation({
    operationId: "getConnectorRootHealth",
    category: "health",
    method: "GET",
    pathTemplate: "/health",
    runtimeOwner: "connector-execution",
    publicOrProtected: "public",
    authenticationRequirement: "none",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    responseSchema: "Health",
    documentationSummary: "Returns Connector Worker health.",
  }),
  getHealth: defineOperation({
    operationId: "getHealth",
    category: "health",
    method: "GET",
    pathTemplate: "/api/health",
    runtimeOwner: "core-api",
    publicOrProtected: "public",
    authenticationRequirement: "none",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    responseSchema: "Health",
    documentationSummary: "Returns Core API health.",
  }),
  getConnectorHealth: defineOperation({
    operationId: "getConnectorHealth",
    category: "health",
    method: "GET",
    pathTemplate: "/api/connector/health",
    runtimeOwner: "connector-execution",
    publicOrProtected: "public",
    authenticationRequirement: "none",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    responseSchema: "Health",
    documentationSummary: "Returns Connector health.",
  }),
  agentChat: defineOperation({
    operationId: "agentChat",
    category: "actions",
    method: "POST",
    pathTemplate: "/api/agent/chat",
    runtimeOwner: "core-api",
    requestSchema: "AgentChatRequest",
    responseSchema: "AgentChatStream",
    auditRequirement: "required",
    documentationSummary: "Runs the bounded agent conversation workflow.",
  }),
  initIntegrationOAuth: defineOperation({
    operationId: "initIntegrationOAuth",
    category: "auth",
    method: "POST",
    pathTemplate: "/api/auth/init-oauth",
    runtimeOwner: "core-api",
    supportedStatus: "unsupported",
    responseSchema: "Unsupported",
    documentationSummary: "Legacy browser OAuth initializer; use server-side provider connections.",
  }),
  getCoreBackendStatus: defineOperation({
    operationId: "getCoreBackendStatus",
    category: "services",
    method: "GET",
    pathTemplate: "/api/backend",
    runtimeOwner: "core-api",
    responseSchema: "BackendStatus",
    documentationSummary: "Returns backend configuration status.",
  }),
  getLegacyTenantInfo: defineOperation({
    operationId: "getLegacyTenantInfo",
    category: "identity",
    method: "GET",
    pathTemplate: "/v1/tenant-info",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "getWorkspace",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Workspace",
    documentationSummary: "Deprecated tenant information compatibility operation.",
  }),
  setLegacyTenantInfo: defineOperation({
    operationId: "setLegacyTenantInfo",
    category: "identity",
    method: "PUT",
    pathTemplate: "/v1/tenant-info",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "getWorkspace",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Workspace",
    documentationSummary: "Deprecated tenant information update operation.",
  }),
  legacyToolRun: defineOperation({
    operationId: "legacyToolRun",
    category: "actions",
    method: "POST",
    pathTemplate: "/v1/tools/run",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "mcp",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated tool execution endpoint.",
  }),
  legacyToolStepRun: defineOperation({
    operationId: "legacyToolStepRun",
    category: "actions",
    method: "POST",
    pathTemplate: "/v1/tools/step/run",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "mcp",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated tool step execution endpoint.",
  }),
  legacyToolStepAbort: defineOperation({
    operationId: "legacyToolStepAbort",
    category: "actions",
    method: "POST",
    pathTemplate: "/v1/tools/step/abort",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "mcp",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated tool step abort endpoint.",
  }),
  legacyToolTransformRun: defineOperation({
    operationId: "legacyToolTransformRun",
    category: "actions",
    method: "POST",
    pathTemplate: "/v1/tools/transform/run",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "mcp",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated transform execution endpoint.",
  }),
  legacyRuns: defineOperation({
    operationId: "legacyRuns",
    category: "runs",
    method: "POST",
    pathTemplate: "/v1/runs",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "listActions",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated run creation endpoint.",
  }),
  legacyToolCreate: defineOperation({
    operationId: "legacyToolCreate",
    category: "actions",
    method: "POST",
    pathTemplate: "/v1/tools",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "mcp",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated tool creation endpoint.",
  }),
  legacyToolUpdate: defineOperation({
    operationId: "legacyToolUpdate",
    category: "actions",
    method: "PUT",
    pathTemplate: "/v1/tools/:id",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "mcp",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated tool update endpoint.",
  }),
  legacySystems: defineOperation({
    operationId: "legacySystems",
    category: "systems",
    method: "POST",
    pathTemplate: "/v1/systems",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "getWorkspace",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated system creation endpoint.",
  }),
  legacyOauthSecrets: defineOperation({
    operationId: "legacyOauthSecrets",
    category: "auth",
    method: "POST",
    pathTemplate: "/v1/oauth/secrets",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "mcpToken",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated OAuth secret endpoint.",
  }),
  legacyOauthSecret: defineOperation({
    operationId: "legacyOauthSecret",
    category: "auth",
    method: "GET",
    pathTemplate: "/v1/oauth/secrets/:uid",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "mcpToken",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated OAuth secret lookup endpoint.",
  }),
  legacyCliSecret: defineOperation({
    operationId: "legacyCliSecret",
    category: "auth",
    method: "GET",
    pathTemplate: "/v1/oauth/cli-secret",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "mcpToken",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated CLI OAuth secret endpoint.",
  }),
  legacySchedules: defineOperation({
    operationId: "legacySchedules",
    category: "services",
    method: "GET",
    pathTemplate: "/v1/schedules",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "listActions",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated schedule listing endpoint.",
  }),
  legacyToolSchedules: defineOperation({
    operationId: "legacyToolSchedules",
    category: "services",
    method: "GET",
    pathTemplate: "/v1/tools/:id/schedules",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "listActions",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated tool schedule endpoint.",
  }),
  legacySummarize: defineOperation({
    operationId: "legacySummarize",
    category: "artifacts",
    method: "POST",
    pathTemplate: "/v1/summarize",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "mcp",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated summarize endpoint.",
  }),
  legacyInitializeUser: defineOperation({
    operationId: "legacyInitializeUser",
    category: "identity",
    method: "POST",
    pathTemplate: "/v1/internal/initializeUser",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "getIdentity",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated internal identity initialization endpoint.",
  }),
  legacyAssignOrgRole: defineOperation({
    operationId: "legacyAssignOrgRole",
    category: "identity",
    method: "POST",
    pathTemplate: "/v1/internal/assignOrgRole",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "getIdentity",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated internal role assignment endpoint.",
  }),
  getReadiness: defineOperation({
    operationId: "getReadiness",
    category: "readiness",
    method: "GET",
    pathTemplate: "/api/readiness",
    runtimeOwner: "core-api",
    publicOrProtected: "public",
    authenticationRequirement: "none",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    responseSchema: "Readiness",
    documentationSummary: "Returns dependency and workspace readiness.",
  }),
  listLegacyTools: defineOperation({
    operationId: "listLegacyTools",
    category: "mcp",
    method: "GET",
    pathTemplate: "/v1/tools",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "mcp",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "ToolList",
    documentationSummary: "Deprecated legacy tool listing.",
  }),
  getLegacyMultiEnvironment: defineOperation({
    operationId: "getLegacyMultiEnvironment",
    category: "systems",
    method: "GET",
    pathTemplate: "/v1/systems/has-multi-env",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "getWorkspace",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "MultiEnvironmentStatus",
    documentationSummary: "Deprecated legacy environment status.",
  }),
  getIdentity: defineOperation({
    operationId: "getIdentity",
    category: "identity",
    method: "GET",
    pathTemplate: "/api/identity",
    runtimeOwner: "core-api",
    responseSchema: "Identity",
    documentationSummary: "Returns the authorized identity.",
  }),
  getWorkspace: defineOperation({
    operationId: "getWorkspace",
    category: "workspace",
    method: "GET",
    pathTemplate: "/api/workspace",
    runtimeOwner: "core-api",
    webMcpAvailability: true,
    remoteMcpAvailability: true,
    responseSchema: "Workspace",
    documentationSummary: "Returns the authorized workspace.",
  }),
  createWorkspace: defineOperation({
    operationId: "createWorkspace",
    category: "workspace",
    method: "POST",
    pathTemplate: "/api/workspace",
    runtimeOwner: "core-api",
    requestSchema: "CreateWorkspaceRequest",
    responseSchema: "Workspace",
    idempotencyRequirement: "required",
    rateLimitCategory: "write",
    auditRequirement: "required",
    documentationSummary: "Creates an authorized workspace.",
  }),
  getCanvas: defineOperation({
    operationId: "getCanvas",
    category: "canvas",
    method: "GET",
    pathTemplate: "/api/canvas/:canvasId",
    runtimeOwner: "core-api",
    responseSchema: "CanvasGraph",
    documentationSummary: "Returns persisted Canvas graph data.",
  }),
  getCanvasAccess: defineOperation({
    operationId: "getCanvasAccess",
    category: "canvas",
    method: "GET",
    pathTemplate: "/api/canvas/access",
    runtimeOwner: "core-api",
    responseSchema: "CanvasAccess",
    documentationSummary: "Returns authorized Canvas access metadata.",
  }),
  getCanvasRealtimeToken: defineOperation({
    operationId: "getCanvasRealtimeToken",
    category: "canvas",
    method: "GET",
    pathTemplate: "/api/canvas/realtime-token",
    runtimeOwner: "core-api",
    responseSchema: "CanvasRealtimeToken",
    documentationSummary: "Returns a scoped Canvas realtime token.",
  }),
  getConsole: defineOperation({
    operationId: "getConsole",
    category: "console",
    method: "GET",
    pathTemplate: "/api/console",
    runtimeOwner: "core-api",
    responseSchema: "ConsoleTimeline",
    documentationSummary: "Returns the authorized console timeline.",
  }),
  listActions: defineOperation({
    operationId: "listActions",
    category: "actions",
    method: "GET",
    pathTemplate: "/api/actions",
    runtimeOwner: "core-api",
    responseSchema: "ActionList",
    paginationSchema: "Pagination",
    webMcpAvailability: true,
    remoteMcpAvailability: true,
    documentationSummary: "Lists persisted actions in the workspace.",
  }),
  listIncidents: defineOperation({
    operationId: "listIncidents",
    category: "incidents",
    method: "GET",
    pathTemplate: "/api/incidents",
    runtimeOwner: "core-api",
    responseSchema: "IncidentList",
    paginationSchema: "Pagination",
    webMcpAvailability: true,
    remoteMcpAvailability: true,
    documentationSummary: "Lists authorized incidents.",
  }),
  createIncident: defineOperation({
    operationId: "createIncident",
    category: "incidents",
    method: "POST",
    pathTemplate: "/api/incidents",
    runtimeOwner: "core-api",
    requestSchema: "CreateIncidentRequest",
    responseSchema: "Incident",
    idempotencyRequirement: "required",
    rateLimitCategory: "write",
    auditRequirement: "required",
    documentationSummary: "Creates an incident record.",
  }),
  getIncident: defineOperation({
    operationId: "getIncident",
    category: "incidents",
    method: "GET",
    pathTemplate: "/api/incidents/:id",
    runtimeOwner: "core-api",
    responseSchema: "Incident",
    webMcpAvailability: true,
    remoteMcpAvailability: true,
    documentationSummary: "Returns one authorized incident.",
  }),
  getIncidentContext: defineOperation({
    operationId: "getIncidentContext",
    category: "incidents",
    method: "GET",
    pathTemplate: "/api/incident/:id/context",
    runtimeOwner: "core-api",
    responseSchema: "IncidentContext",
    webMcpAvailability: true,
    remoteMcpAvailability: true,
    documentationSummary: "Returns evidence-backed incident context.",
  }),
  suggestHotfixes: defineOperation({
    operationId: "suggestHotfixes",
    category: "hotfixes",
    method: "GET",
    pathTemplate: "/api/incident/:id/suggest_hotfixes",
    runtimeOwner: "core-api",
    responseSchema: "HotfixSuggestionList",
    webMcpAvailability: true,
    remoteMcpAvailability: true,
    documentationSummary: "Returns reviewable hotfix suggestions.",
  }),
  evaluateGuardrails: defineOperation({
    operationId: "evaluateGuardrails",
    category: "guardrails",
    method: "POST",
    pathTemplate: "/api/guardrails",
    runtimeOwner: "core-api",
    requestSchema: "GuardrailEvaluationRequest",
    responseSchema: "GuardrailEvaluation",
    rateLimitCategory: "write",
    auditRequirement: "required",
    documentationSummary: "Evaluates policy before consequential work.",
  }),
  requestHotfixApproval: defineOperation({
    operationId: "requestHotfixApproval",
    category: "approvals",
    method: "POST",
    pathTemplate: "/api/incidents/hotfix/approval",
    runtimeOwner: "core-api",
    requestSchema: "HotfixApprovalRequest",
    responseSchema: "Approval",
    idempotencyRequirement: "required",
    rateLimitCategory: "write",
    auditRequirement: "required",
    documentationSummary: "Creates exact-scope hotfix approval.",
  }),
  executeHotfix: defineOperation({
    operationId: "executeHotfix",
    category: "hotfixes",
    method: "POST",
    pathTemplate: "/api/incidents/hotfix",
    runtimeOwner: "core-api",
    requestSchema: "HotfixExecutionRequest",
    responseSchema: "ExecutionResult",
    capabilityRequirement: "incident.hotfix.execute",
    idempotencyRequirement: "required",
    rateLimitCategory: "provider",
    auditRequirement: "required",
    queueRequirement: "producer",
    verificationRequirement: "independent",
    documentationSummary: "Queues an approved hotfix for connector execution and verification.",
  }),
  listIntegrations: defineOperation({
    operationId: "listIntegrations",
    category: "integrations",
    method: "GET",
    pathTemplate: "/api/integrations",
    runtimeOwner: "core-api",
    responseSchema: "IntegrationList",
    paginationSchema: "Pagination",
    webMcpAvailability: true,
    remoteMcpAvailability: true,
    documentationSummary: "Lists connection and capability status.",
  }),
  getMcpConnectionState: defineOperation({
    operationId: "getMcpConnectionState",
    category: "mcpOAuth",
    method: "GET",
    pathTemplate: "/api/mcp/connection",
    runtimeOwner: "core-api",
    responseSchema: "McpConnectionState",
    documentationSummary: "Returns the authenticated user's persisted MCP OAuth state.",
  }),
  getIntegration: defineOperation({
    operationId: "getIntegration",
    category: "integrations",
    method: "GET",
    pathTemplate: "/api/integrations/:providerId",
    runtimeOwner: "core-api",
    responseSchema: "IntegrationDetail",
    providerRequirement: "dynamic",
    documentationSummary: "Returns one persisted provider connection.",
  }),
  verifyIntegration: defineOperation({
    operationId: "verifyIntegration",
    category: "integrations",
    method: "POST",
    pathTemplate: "/api/integrations/:providerId/verify",
    runtimeOwner: "connector-execution",
    responseSchema: "IntegrationDetail",
    providerRequirement: "dynamic",
    idempotencyRequirement: "required",
    auditRequirement: "required",
    verificationRequirement: "independent",
    documentationSummary: "Runs a safe read-only provider verification.",
  }),
  getIntegrationCapabilities: defineOperation({
    operationId: "getIntegrationCapabilities",
    category: "integrations",
    method: "GET",
    pathTemplate: "/api/integrations/:providerId/capabilities",
    runtimeOwner: "core-api",
    responseSchema: "ProviderCapabilities",
    providerRequirement: "dynamic",
    documentationSummary: "Returns persisted provider capability metadata.",
  }),
  getIntegrationResources: defineOperation({
    operationId: "getIntegrationResources",
    category: "integrations",
    method: "GET",
    pathTemplate: "/api/integrations/:providerId/resources",
    runtimeOwner: "core-api",
    responseSchema: "ResourceList",
    providerRequirement: "dynamic",
    paginationSchema: "Pagination",
    documentationSummary: "Returns bounded mapped provider resources.",
  }),
  getIntegrationActivity: defineOperation({
    operationId: "getIntegrationActivity",
    category: "integrations",
    method: "GET",
    pathTemplate: "/api/integrations/:providerId/activity",
    runtimeOwner: "core-api",
    responseSchema: "ActivityList",
    providerRequirement: "dynamic",
    paginationSchema: "Pagination",
    documentationSummary: "Returns provider connection audit activity.",
  }),
  disconnectIntegration: defineOperation({
    operationId: "disconnectIntegration",
    category: "integrations",
    method: "DELETE",
    pathTemplate: "/api/integrations/:providerId/connection",
    runtimeOwner: "connector-execution",
    responseSchema: "IntegrationDetail",
    providerRequirement: "dynamic",
    idempotencyRequirement: "required",
    auditRequirement: "required",
    documentationSummary: "Disconnects a provider connection.",
  }),
  connectNango: defineOperation({
    operationId: "connectNango",
    category: "integrations",
    method: "POST",
    pathTemplate: "/api/integrations/:providerId/connect",
    runtimeOwner: "connector-execution",
    requestSchema: "NangoConnectRequest",
    responseSchema: "Connection",
    idempotencyRequirement: "required",
    rateLimitCategory: "provider",
    auditRequirement: "required",
    providerRequirement: "nango",
    documentationSummary: "Creates a provider connection through Nango.",
  }),
  runSnykScan: defineOperation({
    operationId: "runSnykScan",
    category: "providers",
    method: "POST",
    pathTemplate: "/api/integrations/snyk/scan",
    runtimeOwner: "connector-execution",
    requestSchema: "SnykScanRequest",
    responseSchema: "ProviderResult",
    capabilityRequirement: "snyk.scan",
    providerRequirement: "snyk",
    auditRequirement: "required",
    documentationSummary: "Runs a scoped Snyk scan.",
  }),
  getSnykVulnerabilities: defineOperation({
    operationId: "getSnykVulnerabilities",
    category: "providers",
    method: "GET",
    pathTemplate: "/api/integrations/snyk/vulnerabilities",
    runtimeOwner: "connector-execution",
    responseSchema: "ProviderResult",
    capabilityRequirement: "snyk.read",
    providerRequirement: "snyk",
    webMcpAvailability: true,
    remoteMcpAvailability: true,
    documentationSummary: "Reads Snyk vulnerabilities.",
  }),
  getSnykFix: defineOperation({
    operationId: "getSnykFix",
    category: "providers",
    method: "POST",
    pathTemplate: "/api/integrations/snyk/fix/:vulnerabilityId",
    runtimeOwner: "connector-execution",
    responseSchema: "ProviderResult",
    capabilityRequirement: "snyk.fix",
    providerRequirement: "snyk",
    idempotencyRequirement: "required",
    rateLimitCategory: "provider",
    auditRequirement: "required",
    documentationSummary: "Creates a governed Snyk remediation proposal; it never writes directly.",
  }),
  analyzeSocketPackage: defineOperation({
    operationId: "analyzeSocketPackage",
    category: "providers",
    method: "GET",
    pathTemplate: "/api/integrations/socket/analyze",
    runtimeOwner: "connector-execution",
    responseSchema: "ProviderResult",
    capabilityRequirement: "socket.read",
    providerRequirement: "socket",
    webMcpAvailability: true,
    remoteMcpAvailability: true,
    documentationSummary: "Reads Socket package analysis.",
  }),
  getSocketReport: defineOperation({
    operationId: "getSocketReport",
    category: "providers",
    method: "GET",
    pathTemplate: "/api/integrations/socket/report/:projectId",
    runtimeOwner: "connector-execution",
    responseSchema: "ProviderResult",
    capabilityRequirement: "socket.read",
    providerRequirement: "socket",
    documentationSummary: "Reads a Socket supply-chain report.",
  }),
  detectSocketMalware: defineOperation({
    operationId: "detectSocketMalware",
    category: "providers",
    method: "GET",
    pathTemplate: "/api/integrations/socket/malware",
    runtimeOwner: "connector-execution",
    responseSchema: "ProviderResult",
    capabilityRequirement: "socket.read",
    providerRequirement: "socket",
    documentationSummary: "Reads Socket malware analysis.",
  }),
  getGithubSecurity: defineOperation({
    operationId: "getGithubSecurity",
    category: "providers",
    method: "GET",
    pathTemplate: "/api/integrations/github/security",
    runtimeOwner: "connector-execution",
    responseSchema: "ProviderResult",
    capabilityRequirement: "github.security.read",
    providerRequirement: "github",
    webMcpAvailability: true,
    remoteMcpAvailability: true,
    documentationSummary: "Reads GitHub security alerts by kind.",
  }),
  connectorProviderAction: defineOperation({
    operationId: "connectorProviderAction",
    category: "providers",
    method: "ALL",
    pathTemplate: "/api/integrations/:provider/*",
    runtimeOwner: "connector-execution",
    requestSchema: "ProviderActionRequest",
    responseSchema: "ProviderResult",
    providerRequirement: "dynamic",
    capabilityRequirement: "provider.action",
    idempotencyRequirement: "required",
    rateLimitCategory: "provider",
    auditRequirement: "required",
    verificationRequirement: "independent",
    documentationSummary: "Executes an explicitly allowlisted provider operation.",
  }),
  getBudget: defineOperation({
    operationId: "getBudget",
    category: "budget",
    method: "GET",
    pathTemplate: "/api/payments/budget",
    runtimeOwner: "core-api",
    responseSchema: "Budget",
    documentationSummary: "Returns workspace budget state.",
  }),
  checkBudget: defineOperation({
    operationId: "checkBudget",
    category: "budget",
    method: "POST",
    pathTemplate: "/api/payments/budget/check",
    runtimeOwner: "core-api",
    requestSchema: "BudgetCheckRequest",
    responseSchema: "BudgetCheck",
    rateLimitCategory: "write",
    auditRequirement: "required",
    documentationSummary: "Checks budget policy.",
  }),
  syncWorkspace: defineOperation({
    operationId: "syncWorkspace",
    category: "sync",
    method: "POST",
    pathTemplate: "/api/sync",
    runtimeOwner: "connector-execution",
    requestSchema: "SyncRequest",
    responseSchema: "SyncResult",
    idempotencyRequirement: "required",
    queueRequirement: "producer",
    auditRequirement: "required",
    documentationSummary: "Synchronizes authorized provider resources.",
  }),
  listDocs: defineOperation({
    operationId: "listDocs",
    category: "docs",
    method: "GET",
    pathTemplate: "/api/docs",
    runtimeOwner: "core-api",
    responseSchema: "DocumentList",
    paginationSchema: "Pagination",
    documentationSummary: "Lists workspace documentation.",
  }),
  getDoc: defineOperation({
    operationId: "getDoc",
    category: "docs",
    method: "GET",
    pathTemplate: "/api/docs/:id",
    runtimeOwner: "core-api",
    responseSchema: "Document",
    webMcpAvailability: true,
    remoteMcpAvailability: true,
    documentationSummary: "Returns one workspace document.",
  }),
  createDocProposal: defineOperation({
    operationId: "createDocProposal",
    category: "docs",
    method: "POST",
    pathTemplate: "/api/docs/proposals",
    runtimeOwner: "core-api",
    requestSchema: "DocumentProposalRequest",
    responseSchema: "Proposal",
    idempotencyRequirement: "required",
    auditRequirement: "required",
    documentationSummary: "Creates a reviewable documentation proposal.",
  }),
  streamLogs: defineOperation({
    operationId: "streamLogs",
    category: "logs",
    method: "GET",
    pathTemplate: "/api/logs/stream",
    runtimeOwner: "core-api",
    responseSchema: "LogEventStream",
    auditRequirement: "optional",
    documentationSummary: "Streams authorized operational log events.",
  }),
  getAi: defineOperation({
    operationId: "getAi",
    category: "artifacts",
    method: "GET",
    pathTemplate: "/api/ai",
    runtimeOwner: "core-api",
    supportedStatus: "unsupported",
    responseSchema: "Unsupported",
    documentationSummary: "Reserved AI endpoint; unavailable in this deployment.",
  }),
  getTrpc: defineOperation({
    operationId: "getTrpc",
    category: "artifacts",
    method: "ALL",
    pathTemplate: "/api/trpc",
    runtimeOwner: "core-api",
    supportedStatus: "unsupported",
    responseSchema: "Unsupported",
    documentationSummary: "Reserved tRPC compatibility endpoint; unavailable in this deployment.",
  }),
  getSystemsTunnels: defineOperation({
    operationId: "getSystemsTunnels",
    category: "systems",
    method: "GET",
    pathTemplate: "/v1/tunnels",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "getWorkspace",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated tunnel listing.",
  }),
  getLegacyHooks: defineOperation({
    operationId: "getLegacyHooks",
    category: "webhooks",
    method: "GET",
    pathTemplate: "/v1/hooks",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "mcp",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated hooks endpoint.",
  }),
  unsupportedTunnels: defineOperation({
    operationId: "unsupportedTunnels",
    category: "systems",
    method: "ALL",
    pathTemplate: "/api/tunnels",
    runtimeOwner: "core-api",
    supportedStatus: "unsupported",
    responseSchema: "Unsupported",
    documentationSummary: "Unsupported tunnel capability with structured guidance.",
  }),
  unsupportedTools: defineOperation({
    operationId: "unsupportedTools",
    category: "mcp",
    method: "ALL",
    pathTemplate: "/api/tools",
    runtimeOwner: "core-api",
    supportedStatus: "unsupported",
    responseSchema: "Unsupported",
    documentationSummary: "Unsupported legacy tools capability with structured guidance.",
  }),
  unsupportedRuns: defineOperation({
    operationId: "unsupportedRuns",
    category: "runs",
    method: "ALL",
    pathTemplate: "/api/runs",
    runtimeOwner: "core-api",
    supportedStatus: "unsupported",
    responseSchema: "Unsupported",
    documentationSummary: "Unsupported legacy runs capability with structured guidance.",
  }),
  unsupportedSchedules: defineOperation({
    operationId: "unsupportedSchedules",
    category: "services",
    method: "ALL",
    pathTemplate: "/api/schedules",
    runtimeOwner: "core-api",
    supportedStatus: "unsupported",
    responseSchema: "Unsupported",
    documentationSummary: "Unsupported legacy schedules capability with structured guidance.",
  }),
  unsupportedOauthSecrets: defineOperation({
    operationId: "unsupportedOauthSecrets",
    category: "auth",
    method: "ALL",
    pathTemplate: "/api/oauth/secrets",
    runtimeOwner: "core-api",
    supportedStatus: "unsupported",
    responseSchema: "Unsupported",
    documentationSummary: "Unsupported secret access capability.",
  }),
  unsupportedExtract: defineOperation({
    operationId: "unsupportedExtract",
    category: "artifacts",
    method: "ALL",
    pathTemplate: "/api/extract",
    runtimeOwner: "core-api",
    supportedStatus: "unsupported",
    responseSchema: "Unsupported",
    documentationSummary: "Unsupported extraction capability.",
  }),
  unsupportedSummarize: defineOperation({
    operationId: "unsupportedSummarize",
    category: "artifacts",
    method: "ALL",
    pathTemplate: "/api/summarize",
    runtimeOwner: "core-api",
    supportedStatus: "unsupported",
    responseSchema: "Unsupported",
    documentationSummary: "Unsupported summarization capability.",
  }),
  getLegacyRuns: defineOperation({
    operationId: "getLegacyRuns",
    category: "runs",
    method: "GET",
    pathTemplate: "/v1/runs",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "listActions",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated run listing.",
  }),
  getLegacySystems: defineOperation({
    operationId: "getLegacySystems",
    category: "systems",
    method: "GET",
    pathTemplate: "/v1/systems",
    runtimeOwner: "core-api",
    deprecationStatus: "deprecated",
    replacementOperationId: "getWorkspace",
    sunsetDate: "2026-12-31",
    migrationOwner: "platform",
    clientMigrationStatus: "legacy",
    supportedStatus: "deprecated",
    responseSchema: "Unsupported",
    documentationSummary: "Deprecated systems listing.",
  }),
  requestDeploymentApproval: defineOperation({
    operationId: "requestDeploymentApproval",
    category: "approvals",
    method: "POST",
    pathTemplate: "/api/backend/deploy/approval",
    runtimeOwner: "core-api",
    requestSchema: "DeploymentApprovalRequest",
    responseSchema: "Approval",
    idempotencyRequirement: "required",
    auditRequirement: "required",
    documentationSummary: "Creates exact-scope deployment approval.",
  }),
  deployBackend: defineOperation({
    operationId: "deployBackend",
    category: "deployment",
    method: "POST",
    pathTemplate: "/api/backend/deploy",
    runtimeOwner: "connector-execution",
    requestSchema: "DeploymentRequest",
    responseSchema: "ExecutionResult",
    capabilityRequirement: "deployment.execute",
    idempotencyRequirement: "required",
    queueRequirement: "producer",
    auditRequirement: "required",
    verificationRequirement: "independent",
    documentationSummary: "Executes an approved deployment.",
  }),
  nangoWebhook: defineOperation({
    operationId: "nangoWebhook",
    category: "webhooks",
    method: "POST",
    pathTemplate: "/api/nango/webhook",
    runtimeOwner: "connector-execution",
    publicOrProtected: "public",
    authenticationRequirement: "none",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    responseSchema: "WebhookAccepted",
    rateLimitCategory: "webhook",
    queueRequirement: "producer",
    auditRequirement: "required",
    providerRequirement: "nango",
    documentationSummary: "Accepts a signature-verified Nango webhook.",
  }),
  mcp: defineOperation({
    operationId: "mcp",
    category: "mcp",
    method: "ALL",
    pathTemplate: "/mcp",
    runtimeOwner: "mcp-oauth",
    responseSchema: "McpJsonRpc",
    webMcpAvailability: false,
    remoteMcpAvailability: true,
    auditRequirement: "required",
    documentationSummary: "Serves the authenticated remote MCP resource.",
  }),
  mcpRegister: defineOperation({
    operationId: "mcpRegister",
    category: "mcpOAuth",
    method: "POST",
    pathTemplate: "/register",
    runtimeOwner: "mcp-oauth",
    publicOrProtected: "public",
    authenticationRequirement: "none",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    requestSchema: "McpClientRegistration",
    responseSchema: "McpClient",
    rateLimitCategory: "auth",
    documentationSummary: "Registers a public MCP OAuth client.",
  }),
  mcpAuthorize: defineOperation({
    operationId: "mcpAuthorize",
    category: "mcpOAuth",
    method: "GET",
    pathTemplate: "/authorize",
    runtimeOwner: "mcp-oauth",
    publicOrProtected: "public",
    authenticationRequirement: "optional",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    responseSchema: "Redirect",
    rateLimitCategory: "auth",
    documentationSummary: "Starts MCP authorization and consent.",
  }),
  mcpConsent: defineOperation({
    operationId: "mcpConsent",
    category: "mcpOAuth",
    method: "POST",
    pathTemplate: "/authorize/consent",
    runtimeOwner: "mcp-oauth",
    publicOrProtected: "public",
    authenticationRequirement: "required",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    requestSchema: "McpConsentRequest",
    responseSchema: "Redirect",
    rateLimitCategory: "auth",
    auditRequirement: "required",
    documentationSummary: "Records authenticated MCP consent.",
  }),
  mcpToken: defineOperation({
    operationId: "mcpToken",
    category: "mcpOAuth",
    method: "POST",
    pathTemplate: "/token",
    runtimeOwner: "mcp-oauth",
    publicOrProtected: "public",
    authenticationRequirement: "none",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    requestSchema: "McpTokenRequest",
    responseSchema: "McpToken",
    rateLimitCategory: "auth",
    auditRequirement: "required",
    documentationSummary: "Exchanges an MCP authorization code or refresh token.",
  }),
  mcpRevoke: defineOperation({
    operationId: "mcpRevoke",
    category: "mcpOAuth",
    method: "POST",
    pathTemplate: "/revoke",
    runtimeOwner: "mcp-oauth",
    requestSchema: "McpRevokeRequest",
    responseSchema: "Revoked",
    rateLimitCategory: "auth",
    auditRequirement: "required",
    documentationSummary: "Revokes the current MCP connection.",
  }),
  mcpAuthorizationMetadata: defineOperation({
    operationId: "mcpAuthorizationMetadata",
    category: "mcpOAuth",
    method: "GET",
    pathTemplate: "/.well-known/oauth-authorization-server",
    runtimeOwner: "mcp-oauth",
    publicOrProtected: "public",
    authenticationRequirement: "none",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    responseSchema: "McpAuthorizationServerMetadata",
    rateLimitCategory: "auth",
    documentationSummary: "Publishes MCP OAuth authorization metadata.",
  }),
  mcpResourceMetadata: defineOperation({
    operationId: "mcpResourceMetadata",
    category: "mcpOAuth",
    method: "GET",
    pathTemplate: "/.well-known/oauth-protected-resource",
    runtimeOwner: "mcp-oauth",
    publicOrProtected: "public",
    authenticationRequirement: "none",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    responseSchema: "McpProtectedResourceMetadata",
    rateLimitCategory: "auth",
    documentationSummary: "Publishes protected MCP resource metadata.",
  }),
  mcpResourceMetadataForMcp: defineOperation({
    operationId: "mcpResourceMetadataForMcp",
    category: "mcpOAuth",
    method: "GET",
    pathTemplate: "/.well-known/oauth-protected-resource/mcp",
    runtimeOwner: "mcp-oauth",
    publicOrProtected: "public",
    authenticationRequirement: "none",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    responseSchema: "McpProtectedResourceMetadata",
    rateLimitCategory: "auth",
    documentationSummary: "Publishes MCP resource metadata for the resource path.",
  }),
  mcpChallenge: defineOperation({
    operationId: "mcpChallenge",
    category: "mcpOAuth",
    method: "GET",
    pathTemplate: "/.well-known/openai-apps-challenge",
    runtimeOwner: "mcp-oauth",
    publicOrProtected: "public",
    authenticationRequirement: "none",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    responseSchema: "Challenge",
    documentationSummary: "Publishes the configured OpenAI app challenge.",
  }),
  mcpAuthorizationRequest: defineOperation({
    operationId: "mcpAuthorizationRequest",
    category: "mcpOAuth",
    method: "GET",
    pathTemplate: "/authorize/request/:requestId",
    runtimeOwner: "mcp-oauth",
    publicOrProtected: "public",
    authenticationRequirement: "optional",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    responseSchema: "Redirect",
    rateLimitCategory: "auth",
    documentationSummary: "Resumes an MCP authorization request.",
  }),
  mcpAuthorizationRequestApi: defineOperation({
    operationId: "mcpAuthorizationRequestApi",
    category: "mcpOAuth",
    method: "GET",
    pathTemplate: "/api/mcp/authorize/request/:requestId",
    runtimeOwner: "mcp-oauth",
    publicOrProtected: "public",
    authenticationRequirement: "optional",
    organizationScopeRequirement: false,
    workspaceScopeRequirement: false,
    responseSchema: "Redirect",
    rateLimitCategory: "auth",
    documentationSummary: "Resumes an MCP authorization request through the API proxy.",
  }),
  legacyToolRunById: defineLegacyOperation({
    operationId: "legacyToolRunById",
    category: "actions",
    method: "POST",
    pathTemplate: "/v1/tools/:id/run",
    runtimeOwner: "core-api",
    responseSchema: "ToolResult",
    documentationSummary: "Legacy tool execution compatibility operation.",
  }),
  legacyRunCancel: defineLegacyOperation({
    operationId: "legacyRunCancel",
    category: "runs",
    method: "POST",
    pathTemplate: "/v1/runs/:id/cancel",
    runtimeOwner: "core-api",
    responseSchema: "Run",
    documentationSummary: "Legacy run cancellation compatibility operation.",
  }),
  legacyRunGet: defineLegacyOperation({
    operationId: "legacyRunGet",
    category: "runs",
    method: "GET",
    pathTemplate: "/v1/runs/:id",
    runtimeOwner: "core-api",
    responseSchema: "Run",
    documentationSummary: "Legacy run lookup compatibility operation.",
  }),
  legacyToolGet: defineLegacyOperation({
    operationId: "legacyToolGet",
    category: "actions",
    method: "GET",
    pathTemplate: "/v1/tools/:id",
    runtimeOwner: "core-api",
    responseSchema: "Tool",
    documentationSummary: "Legacy tool lookup compatibility operation.",
  }),
  legacyToolDelete: defineLegacyOperation({
    operationId: "legacyToolDelete",
    category: "actions",
    method: "DELETE",
    pathTemplate: "/v1/tools/:id",
    runtimeOwner: "core-api",
    responseSchema: "Success",
    documentationSummary: "Legacy tool deletion compatibility operation.",
  }),
  legacyToolRename: defineLegacyOperation({
    operationId: "legacyToolRename",
    category: "actions",
    method: "POST",
    pathTemplate: "/v1/tools/:id/rename",
    runtimeOwner: "core-api",
    responseSchema: "Tool",
    documentationSummary: "Legacy tool rename compatibility operation.",
  }),
  legacySystemsList: defineLegacyOperation({
    operationId: "legacySystemsList",
    category: "systems",
    method: "GET",
    pathTemplate: "/v1/systems",
    runtimeOwner: "core-api",
    responseSchema: "SystemList",
    paginationSchema: "Pagination",
    documentationSummary: "Legacy systems list compatibility operation.",
  }),
  legacySystemGet: defineLegacyOperation({
    operationId: "legacySystemGet",
    category: "systems",
    method: "GET",
    pathTemplate: "/v1/systems/:id",
    runtimeOwner: "core-api",
    responseSchema: "System",
    documentationSummary: "Legacy system lookup compatibility operation.",
  }),
  legacySystemUpdate: defineLegacyOperation({
    operationId: "legacySystemUpdate",
    category: "systems",
    method: "PATCH",
    pathTemplate: "/v1/systems/:id",
    runtimeOwner: "core-api",
    responseSchema: "System",
    documentationSummary: "Legacy system update compatibility operation.",
  }),
  legacySystemDelete: defineLegacyOperation({
    operationId: "legacySystemDelete",
    category: "systems",
    method: "DELETE",
    pathTemplate: "/v1/systems/:id",
    runtimeOwner: "core-api",
    responseSchema: "Success",
    documentationSummary: "Legacy system deletion compatibility operation.",
  }),
  legacyOAuthTemplateCredentials: defineLegacyOperation({
    operationId: "legacyOAuthTemplateCredentials",
    category: "auth",
    method: "GET",
    pathTemplate: "/v1/oauth/templates/:id/credentials",
    runtimeOwner: "core-api",
    responseSchema: "OAuthCredentials",
    documentationSummary: "Legacy OAuth template credential lookup.",
  }),
  legacySystemDocumentationSearch: defineLegacyOperation({
    operationId: "legacySystemDocumentationSearch",
    category: "docs",
    method: "POST",
    pathTemplate: "/v1/systems/:id/documentation/search",
    runtimeOwner: "core-api",
    responseSchema: "DocumentSearchResult",
    documentationSummary: "Legacy system documentation search.",
  }),
  legacySystemDocumentationScrape: defineLegacyOperation({
    operationId: "legacySystemDocumentationScrape",
    category: "docs",
    method: "POST",
    pathTemplate: "/v1/systems/:id/documentation/scrape",
    runtimeOwner: "core-api",
    responseSchema: "Job",
    documentationSummary: "Legacy documentation scrape job.",
  }),
  legacySystemDocumentationOpenApi: defineLegacyOperation({
    operationId: "legacySystemDocumentationOpenApi",
    category: "docs",
    method: "POST",
    pathTemplate: "/v1/systems/:id/documentation/openapi",
    runtimeOwner: "core-api",
    responseSchema: "Job",
    documentationSummary: "Legacy OpenAPI documentation import.",
  }),
  legacySystemFileReferencesCreate: defineLegacyOperation({
    operationId: "legacySystemFileReferencesCreate",
    category: "artifacts",
    method: "POST",
    pathTemplate: "/v1/systems/:id/file-references",
    runtimeOwner: "core-api",
    responseSchema: "FileReferenceList",
    documentationSummary: "Legacy file reference creation.",
  }),
  legacySystemFileReferencesList: defineLegacyOperation({
    operationId: "legacySystemFileReferencesList",
    category: "artifacts",
    method: "GET",
    pathTemplate: "/v1/systems/:id/file-references",
    runtimeOwner: "core-api",
    responseSchema: "FileReferenceList",
    documentationSummary: "Legacy file reference listing.",
  }),
  legacySystemFileReferenceDelete: defineLegacyOperation({
    operationId: "legacySystemFileReferenceDelete",
    category: "artifacts",
    method: "DELETE",
    pathTemplate: "/v1/systems/:systemId/file-references/:fileId",
    runtimeOwner: "core-api",
    responseSchema: "Success",
    documentationSummary: "Legacy file reference deletion.",
  }),
  legacyFileReferenceContent: defineLegacyOperation({
    operationId: "legacyFileReferenceContent",
    category: "artifacts",
    method: "GET",
    pathTemplate: "/v1/file-references/:id",
    runtimeOwner: "core-api",
    responseSchema: "FileReference",
    documentationSummary: "Legacy file reference content lookup.",
  }),
  legacyAuthenticate: defineLegacyOperation({
    operationId: "legacyAuthenticate",
    category: "auth",
    method: "POST",
    pathTemplate: "/v1/authenticate",
    runtimeOwner: "core-api",
    responseSchema: "Identity",
    documentationSummary: "Legacy API-key authentication compatibility operation.",
  }),
} as const satisfies Record<string, OperationDefinition>;

export type OperationId = keyof typeof operations;
export const operationRegistry = Object.values(operations);

export function operationPath<T extends OperationId>(
  operationId: T,
  params: Record<string, string> = {},
) {
  let path: string = operations[operationId].pathTemplate;
  for (const [key, value] of Object.entries(params))
    path = path.replace(`:${key}`, encodeURIComponent(value));
  return path;
}

export type ServiceOriginName =
  | "frontendOrigin"
  | "coreApiOrigin"
  | "connectorApiOrigin"
  | "mcpResourceOrigin"
  | "oauthIssuerOrigin"
  | "webhookOrigin";
export type ServiceOriginRegistry = Readonly<Record<ServiceOriginName, string>>;
