PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS organizations (id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS memberships (organization_id TEXT NOT NULL, user_id TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'member', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (organization_id, user_id), FOREIGN KEY (organization_id) REFERENCES organizations(id));
CREATE TABLE IF NOT EXISTS agents (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (organization_id) REFERENCES organizations(id));
CREATE TABLE IF NOT EXISTS tools (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL, input_schema TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (organization_id) REFERENCES organizations(id));
CREATE TABLE IF NOT EXISTS actions (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, actor_type TEXT NOT NULL, actor_id TEXT NOT NULL, tool_id TEXT, incident_id TEXT, action_type TEXT NOT NULL, input_json TEXT NOT NULL DEFAULT '{}', output_json TEXT NOT NULL DEFAULT '{}', status TEXT NOT NULL, guardrail_decision_json TEXT NOT NULL DEFAULT '{}', approval_state TEXT NOT NULL DEFAULT 'not_required', related_resource_type TEXT, related_resource_id TEXT, summary TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at TEXT, FOREIGN KEY (organization_id) REFERENCES organizations(id));
CREATE TRIGGER IF NOT EXISTS actions_immutable_update BEFORE UPDATE ON actions BEGIN SELECT RAISE(ABORT, 'actions are append-only'); END;
CREATE TRIGGER IF NOT EXISTS actions_immutable_delete BEFORE DELETE ON actions BEGIN SELECT RAISE(ABORT, 'actions are append-only'); END;
CREATE TABLE IF NOT EXISTS incidents (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, title TEXT NOT NULL, service TEXT NOT NULL, severity TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', context TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (organization_id) REFERENCES organizations(id));
CREATE TABLE IF NOT EXISTS docs (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, incident_id TEXT, title TEXT NOT NULL, body TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'proposal', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (organization_id) REFERENCES organizations(id));
CREATE TABLE IF NOT EXISTS budgets (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, period TEXT NOT NULL, limit_amount INTEGER NOT NULL, spent_amount INTEGER NOT NULL DEFAULT 0, FOREIGN KEY (organization_id) REFERENCES organizations(id));
CREATE TABLE IF NOT EXISTS spend_log (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, agent_id TEXT, amount INTEGER NOT NULL, reason TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (organization_id) REFERENCES organizations(id));
CREATE TABLE IF NOT EXISTS integrations (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, provider TEXT NOT NULL, connection_id TEXT, status TEXT NOT NULL DEFAULT 'pending', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (organization_id) REFERENCES organizations(id));
CREATE TABLE IF NOT EXISTS sync_jobs (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, provider TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued', cursor TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (organization_id) REFERENCES organizations(id));
